### PR TITLE
adding power spectrum utils functions

### PR DESCRIPTION
**Pull request by b-remy**
Adds code to compute power spectrum from a map and generate the `ps_map` useful for decoder renormalization.

Code renormalizing `map1` with `map2`'s power spectrum
```python
from learn2map.utils import measure_power_spectrum, make_ps_map

# N = map1.shape[0]
ps_map1 = make_ps_map(measure_power_spectrum(map1), N)
ps_map2 = make_ps_map(measure_power_spectrum(map2), N)

cancel_ps_map = jnp.fft.ifft2(jnp.fft.fft2(map1) / jnp.sqrt(ps_map1)).real
apply_ps_map = jnp.fft.ifft2(jnp.fft.fft2(map1) / jnp.sqrt(ps_map1) * jnp.sqrt(ps_map2)).real
```
image

### CODE REVIEW

**Comment by Justinezgh** [comment]
There is an issue while jiting with `bincount` from the [doc](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.bincount.html): 

> **length** ([int](https://docs.python.org/3/library/functions.html#int) | None) – the length of the output counts array. Must be specified statically for bincount to be used with [jax.jit()](https://jax.readthedocs.io/en/latest/_autosummary/jax.jit.html#jax.jit) and other JAX transformations.

**Comment by Justinezgh** [comment]
We should to something like this (similarly to [this](https://github.com/google/jax/blob/300d06a5051adeba44da0df8b8852ec684353422/jax/_src/numpy/lax_numpy.py#L2068))
```python 
jit_bincount = jax.jit(jnp.bincount, static_argnames=['length'])

@jax.jit
def radial_profile(power_spectrum_2d):
    """
    Compute the radial profile of 2d image
    :param data: 2d image
    :return: radial profile
    """
    center = power_spectrum_2d.shape[0]/2
    v, u = jnp.indices((power_spectrum_2d.shape))
    k = jnp.sqrt((u - center)**2 + (v - center)**2)
    k = k.astype('int32')
    
    length = max(0, k.size and jnp.array(k.max(), int) + 1)
    tbin = jit_bincount(k.ravel(), power_spectrum_2d.ravel(), length=length)
    nr = jit_bincount(k.ravel(), length=length)
    radialprofile = tbin / nr
    return radialprofile
```

but now I have issues because I am using `bool`

**Comment by b-remy** [comment]
Forgot to test jit 🤦‍♂️Should be working now and do exactly the same operations as before!

**Comment by Justinezgh** [comment]
ok it works :)

**Pull request merged**
